[build]
  command = "npm run build"
  publish = "build"
  [build.environment]
    CI = "false"
    REACT_APP_SERVER_URL = "https://kevryn-ide-production.up.railway.app"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Access-Control-Allow-Origin = "*"
