import React, { useMemo, useState } from 'react';
import axios from 'axios';
import { FaBullhorn, FaCheckCircle, FaSpinner, FaTimes } from 'react-icons/fa';
const BroadcastProposalPanel = ({ token, onClose }) => {
 const api = useMemo(() => axios.create({ baseURL: (process.env.REACT_APP_SERVER_URL || '').trim(), headers: { Authorization: `Bearer ${token}` } }), [token]);
 const [form,setForm]=useState({title:'',message:'',targetRole:'all',priority:'normal'}),[preview,setPreview]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const update=k=>e=>{setForm(p=>({...p,[k]:e.target.value}));setPreview(null)};
 const review=async()=>{setBusy(true);setError('');try{setPreview((await api.post('/api/management-ai/broadcast/preview',form)).data)}catch(e){setError(e.response?.data?.error||'Could not prepare announcement.')}finally{setBusy(false)}};
 const confirm=async()=>{setBusy(true);setError('');try{const r=await api.post('/api/management-ai/broadcast/confirm',form);setPreview({...preview,sent:true,recipients:r.data.recipients})}catch(e){setError(e.response?.data?.error||'Could not send announcement.')}finally{setBusy(false)}};
 const input={width:'100%',boxSizing:'border-box',border:'1px solid #d8dfec',borderRadius:7,padding:9,fontSize:12,outline:0};
 return <div style={{position:'fixed',zIndex:21000,inset:0,display:'grid',placeItems:'center',padding:20,background:'rgba(9,13,30,.47)',backdropFilter:'blur(5px)'}}><section style={{width:'min(520px,96vw)',borderRadius:17,overflow:'hidden',background:'#f8faff',boxShadow:'0 24px 80px rgba(0,0,0,.36)'}}><header style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:'16px 19px',borderBottom:'1px solid #e0e5ef'}}><div><strong style={{color:'#283655'}}><FaBullhorn color="#6656df"/> Institution announcement</strong><small style={{display:'block',marginTop:4,color:'#7d899f',fontSize:10}}>Review recipients before sending.</small></div><button onClick={onClose} style={{border:0,background:'transparent',cursor:'pointer'}}><FaTimes/></button></header><div style={{padding:19,display:'grid',gap:11}}><input style={input} placeholder="Announcement title" value={form.title} onChange={update('title')}/><textarea style={{...input,minHeight:96,resize:'vertical'}} placeholder="Write the message for your institution…" value={form.message} onChange={update('message')}/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><select style={input} value={form.targetRole} onChange={update('targetRole')}><option value="all">Students and faculty</option><option value="student">Students only</option><option value="faculty">Faculty only</option></select><select style={input} value={form.priority} onChange={update('priority')}><option value="normal">Normal</option><option value="important">Important</option><option value="urgent">Urgent</option></select></div><button disabled={busy} onClick={review} style={{border:0,borderRadius:8,padding:10,color:'#fff',background:'#6254df',fontWeight:700,cursor:'pointer'}}>{busy?<FaSpinner/>:'Review announcement'}</button>{preview&&<div style={{padding:12,border:'1px solid #d7cffb',borderRadius:9,background:'#f4f1ff',fontSize:12,color:'#4d487b'}}>{preview.sent?<><FaCheckCircle color="#189363"/> Sent to {preview.recipients} recipient(s) and added to audit history.</>:<><strong>{preview.recipients} recipient(s)</strong> will receive this {preview.priority} announcement.<button onClick={confirm} disabled={busy} style={{display:'block',marginTop:9,border:0,borderRadius:6,padding:'8px 10px',color:'#fff',background:'#18895f',fontWeight:700,cursor:'pointer'}}>Confirm & send</button></>}</div>}{error&&<p style={{margin:0,color:'#c13d57',fontSize:11}}>{error}</p>}</div></section></div>;
}; export default BroadcastProposalPanel;
