import React, { useEffect, useMemo, useState } from 'react';
import axios from 'axios';
import { FaCheckCircle, FaExclamationTriangle, FaSpinner, FaTimes } from 'react-icons/fa';

const TimetableProposalPanel = ({ token, onClose }) => {
    const rawBase = (process.env.REACT_APP_SERVER_URL || '').trim();
    const api = useMemo(() => axios.create({ baseURL: rawBase, headers: { Authorization: `Bearer ${token}` } }), [rawBase, token]);
    const [context, setContext] = useState(null);
    const [form, setForm] = useState({ department: '', year: '', section: '', subjectName: '', subjectCode: '', facultyId: '', labRoom: '', dayOfWeek: 'Monday', startTime: '09:00', endTime: '11:00' });
    const [proposal, setProposal] = useState(null);
    const [busy, setBusy] = useState(false);
    const [error, setError] = useState('');
    useEffect(() => { api.get('/api/management-ai/timetable/context').then(result => setContext(result.data)).catch(err => setError(err.response?.data?.error || 'Could not load timetable data.')); }, []);
    const update = key => event => { setForm(previous => ({ ...previous, [key]: event.target.value })); setProposal(null); };
    const years = [...new Set((context?.structures || []).filter(item => item.department === form.department).map(item => item.year))];
    const sections = context?.structures?.find(item => item.department === form.department && String(item.year) === String(form.year))?.sections || [];
    const preview = async () => { setBusy(true); setError(''); try { const result = await api.post('/api/management-ai/timetable/preview', form); setProposal(result.data); } catch (err) { setError(err.response?.data?.error || 'Could not validate this timetable entry.'); } finally { setBusy(false); } };
    const confirm = async () => { setBusy(true); setError(''); try { await api.post('/api/management-ai/timetable/confirm', form); setProposal({ safeToApply: true, warnings: [], confirmed: true }); } catch (err) { setError(err.response?.data?.error || 'Could not create this timetable entry.'); } finally { setBusy(false); } };
    const field = (label, key, children) => <label style={{ display: 'grid', gap: 5, color: '#63718b', fontSize: 10, fontWeight: 750, textTransform: 'uppercase', letterSpacing: '.05em' }}>{label}{children || <input value={form[key]} onChange={update(key)} />}</label>;
    const controlStyle = { minHeight: 36, border: '1px solid #d9dfeb', borderRadius: 7, padding: '0 9px', color: '#263452', background: '#fff', outline: 'none', fontSize: 12 };
    return <div style={{ position: 'fixed', zIndex: 21000, inset: 0, display: 'grid', placeItems: 'center', padding: 20, background: 'rgba(9,13,30,.47)', backdropFilter: 'blur(5px)' }}><section style={{ width: 'min(650px,96vw)', maxHeight: '88vh', overflow: 'auto', borderRadius: 18, background: '#f8faff', boxShadow: '0 24px 80px rgba(0,0,0,.36)' }}><header style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '17px 20px', borderBottom: '1px solid #e0e5ef' }}><div><strong style={{ color: '#263453', fontSize: 16 }}>Conflict-free timetable planner</strong><small style={{ display: 'block', marginTop: 3, color: '#7b879d', fontSize: 11 }}>KevRyn checks faculty, room, and cohort conflicts before creating anything.</small></div><button onClick={onClose} style={{ border: 0, color: '#6e7890', background: 'transparent', cursor: 'pointer' }}><FaTimes /></button></header><div style={{ padding: 20 }}>
        {!context ? <p style={{ color: '#71809b', fontSize: 12 }}><FaSpinner /> Loading institutional timetable context…</p> : <><div style={{ display: 'grid', gridTemplateColumns: 'repeat(2,minmax(0,1fr))', gap: 12 }}>{field('Department', 'department', <select style={controlStyle} value={form.department} onChange={update('department')}><option value="">Select department</option>{[...new Set(context.structures.map(item => item.department))].map(value => <option key={value}>{value}</option>)}</select>)}{field('Year', 'year', <select style={controlStyle} value={form.year} onChange={update('year')}><option value="">Select year</option>{years.map(value => <option key={value}>{value}</option>)}</select>)}{field('Section', 'section', <select style={controlStyle} value={form.section} onChange={update('section')}><option value="">Select section</option>{sections.map(value => <option key={value}>{value}</option>)}</select>)}{field('Subject name', 'subjectName')}{field('Subject code', 'subjectCode')}{field('Faculty', 'facultyId', <select style={controlStyle} value={form.facultyId} onChange={update('facultyId')}><option value="">Select faculty</option>{context.faculty.map(item => <option key={item._id} value={item._id}>{item.username}</option>)}</select>)}{field('Lab room', 'labRoom', <select style={controlStyle} value={form.labRoom} onChange={update('labRoom')}><option value="">Select room</option>{context.rooms.map(item => <option key={item._id} value={item.name}>{item.name} · {item.capacity}</option>)}</select>)}{field('Day', 'dayOfWeek', <select style={controlStyle} value={form.dayOfWeek} onChange={update('dayOfWeek')}>{['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map(value => <option key={value}>{value}</option>)}</select>)}{field('Start time', 'startTime', <input style={controlStyle} type="time" value={form.startTime} onChange={update('startTime')} />)}{field('End time', 'endTime', <input style={controlStyle} type="time" value={form.endTime} onChange={update('endTime')} />)}</div><button disabled={busy} onClick={preview} style={{ width: '100%', marginTop: 17, border: 0, borderRadius: 8, padding: 11, color: '#fff', background: '#6154df', fontWeight: 750, cursor: 'pointer' }}>{busy ? <FaSpinner /> : 'Check conflicts & prepare proposal'}</button></>}
        {proposal && <div style={{ marginTop: 16, padding: 13, border: `1px solid ${proposal.safeToApply ? '#aee7cf' : '#f5c3c9'}`, borderRadius: 10, background: proposal.safeToApply ? '#effcf6' : '#fff5f5' }}>{proposal.confirmed ? <><FaCheckCircle color="#20a36d" /> <strong style={{ color: '#177555', marginLeft: 6 }}>Timetable entry created and audited.</strong></> : proposal.safeToApply ? <><FaCheckCircle color="#20a36d" /> <strong style={{ color: '#177555', marginLeft: 6 }}>Safe to apply — no conflicts found.</strong><button disabled={busy} onClick={confirm} style={{ display: 'block', marginTop: 10, border: 0, borderRadius: 7, padding: '8px 10px', color: '#fff', background: '#198b5e', fontWeight: 700, cursor: 'pointer' }}>Confirm & create timetable entry</button></> : <><strong style={{ color: '#b84457' }}><FaExclamationTriangle /> Resolve these conflicts first</strong><ul style={{ margin: '8px 0 0', paddingLeft: 18, color: '#8c5760', fontSize: 11 }}>{proposal.warnings.map((warning, index) => <li key={index}>{warning.message}</li>)}</ul></>}</div>}{error && <p style={{ margin: '12px 0 0', color: '#c23c57', fontSize: 11 }}>{error}</p>}</div></section></div>;
};
export default TimetableProposalPanel;
