const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const File = require('../File');
const User = require('../User');
const LabSession = require('../LabSessionModel');

/**
 * Generates a PDF Lab Record for a specific student in a session.
 * @param {string} sessionId - The ID of the Lab Session
 * @param {string} username - The student's username
 * @param {object} res - Express response object to stream the PDF to
 */
const generateLabReport = async (sessionId, username, res) => {
    try {
        const session = await LabSession.findById(sessionId);
        if (!session) throw new Error("Session not found");

        const user = await User.findOne({ username });
        if (!user) throw new Error("Student not found");

        // Fetch student files filtered by courseId if the session is linked to one
        const query = { owner: user._id };
        if (session.courseId) {
            query.courseId = session.courseId;
        } else {
            // Fallback: if no courseId, maybe it's an older session or general lab
            // and we still use names or root. But let's prioritize isolation.
            query.courseId = { $exists: false };
        }
        const files = await File.find(query);

        // Find student activity in this session
        const studentActivity = session.activeStudents.find(s => s.username === username);
        const loginTime = studentActivity?.loginTime ? new Date(studentActivity.loginTime).toLocaleString() : "N/A";
        const status = studentActivity?.currentStatus || "Unknown";

        // Create PDF
        const doc = new PDFDocument({ margin: 50 });

        // Stream to response
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename=LabRecord_${username}_${Date.now()}.pdf`);
        doc.pipe(res);

        // --- HEADER ---
        doc.fontSize(20).text('Vayu Lab Record', { align: 'center', underline: true });
        doc.moveDown();

        doc.fontSize(12).text(`Session: ${session.sessionName}`);
        doc.text(`Subject: ${session.subject} | Semester: ${session.semester}`);
        doc.text(`Date: ${new Date().toLocaleDateString()}`);
        doc.moveDown();

        doc.fontSize(14).text('Student Details', { underline: true });
        doc.fontSize(12).text(`Name: ${username}`); // Using username as name for now
        doc.text(`ID: ${user._id}`);
        doc.text(`Login Time: ${loginTime}`);
        doc.text(`Status: ${status.toUpperCase()}`);
        doc.moveDown();

        // --- CODE SECTION ---
        doc.fontSize(14).text('Submitted Code Files', { underline: true });
        doc.moveDown();

        if (files.length === 0) {
            doc.fontSize(12).text("No files submitted.");
        } else {
            files.forEach((file, index) => {
                doc.fontSize(12).font('Helvetica-Bold').text(`File ${index + 1}: ${file.name}`);
                doc.fontSize(10).font('Helvetica').text(`Type: ${file.type} | Last Modified: ${new Date(file.lastActivity).toLocaleString()}`);

                // Code Box
                doc.moveDown(0.5);
                const codeContent = file.content || "// Empty file";

                // Simple background for code check
                const y = doc.y;
                doc.rect(50, y, 500, Math.min(300, doc.heightOfString(codeContent) + 20))
                    .fill('#f5f5f5');

                doc.fillColor('black')
                    .text(codeContent, 60, y + 10, {
                        width: 480,
                        lineBreak: true,
                        height: 300 // Limit height per file to avoid huge PDFs? Or let it flow. PAGE BREAKS are tricky.
                    });

                // Reset standard text
                doc.moveDown(2);
            });
        }

        // --- FOOTER ---
        const footerText = "Generated by Vayu Lab Monitor | Kevryn IDE";
        doc.fontSize(10).text(footerText, 50, doc.page.height - 50, { align: 'center', color: 'gray' });

        doc.end();

    } catch (error) {
        console.error("PDF Generation Error:", error);
        if (!res.headersSent) res.status(500).send("Failed to generate report");
    }
};

module.exports = { generateLabReport };
